//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _RealmDigital.DataAccessLayer.Framework.EntityFrameworkModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AddressBookEntities : DbContext
    {
        public AddressBookEntities()
            : base("name=AddressBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressBook> AddressBooks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<spGetUserContactList_Result> spGetUserContactList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetUserContactList_Result>("spGetUserContactList");
        }
    
        public virtual ObjectResult<spSeachContactList_Result> spSeachContactList(string seachKeyWord)
        {
            var seachKeyWordParameter = seachKeyWord != null ?
                new ObjectParameter("SeachKeyWord", seachKeyWord) :
                new ObjectParameter("SeachKeyWord", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSeachContactList_Result>("spSeachContactList", seachKeyWordParameter);
        }
    }
}
